compute:
    config_path:
        - /etc/nova
        - /var/lib/nova
    database:
        - nova
        - nova_api

glance:
    config_path:
        - /etc/glance
        - /var/lib/glance
    database:
        - glance

keystone:
    config_path:
        - /etc/keystone
        - /var/lib/keystone
    database:
        - keystone    

cinder:
    config_path:
        - /etc/cinder
        - /var/lib/cinder
    database:
        - cinder

neutron:
    config_path:
        - /etc/neutron
        - /var/lib/neutron
    database:
        - neutron
    
swift:
    config_path:
        - /etc/swift
    database:
        - swift

ceilometer:
    config_path:
        - /etc/ceilometer
    database:
        - gnocchi 

Orchestration:
    config_path:
        - /etc/heat/
    database:
        - heat   
